apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: morgan-elk
  name: elasticsearch-data
  labels:
    app: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data
  replicas: 3
  template:
    metadata:
      labels:
        app: elasticsearch
        role: data  
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true	  
      - name: init-setup-data
        image: busybox 	  
        command: ["sh", "-c", "chmod -R 777 /data"]
        volumeMounts:
        - name: storage
          mountPath: /data
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role				
                  operator: In
                  values:		
                  - data
              topologyKey: kubernetes.io/hostname			  
      containers:
      - name: elasticsearch-data
        securityContext:
          privileged: false
        image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.4
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "cluster.name"
          value: "morgan-elk"
        - name: node.master
          value: "false"
        - name: node.ingest
          value: "false"
        - name: node.data
          value: "true"  
        - name: search.remote.connect
          value: "false"
        - name: http.enabled
          value: "false"		  
        - name: network.host
          value: 0.0.0.0
        - name: discovery.zen.ping.unicast.hosts
          value: "es-master-transport.morgan-elk.svc.cluster.local"		  
        - name: "ES_JAVA_OPTS"
          value: "-Xms3G -Xmx3G"
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http		  
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10		  
        volumeMounts:
        - name: storage
          mountPath: /usr/share/elasticsearch/data
          subPath: data
      terminationGracePeriodSeconds: 120	  
  volumeClaimTemplates:
  - metadata:
      name: storage        
    spec:
      accessModes: [ "ReadWriteOnce" ]      
      resources:
        requests:
          storage: 100Gi

