apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: efk
  name: elk-ingress
  annotations:    
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: <LOADBALANCE_DNS_NAME>
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: 5601
      - path: /elasticsearch
        backend:
          serviceName: es-master-http
          servicePort: 9200
